# cloudbuild.yaml
#
steps:

 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build','-t', 'gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-weekly-report-api:$COMMIT_SHA', '.']
   dir: 'prod'
   timeout: 1200s
   
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-weekly-report-api:$COMMIT_SHA']
   
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args: ['run','deploy','ccc-weekly-report-api', '--image=gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-weekly-report-api:$COMMIT_SHA', '--cpu=2','--memory=8192Mi', '--region=us-central1', '--service-account=qa-qc-prod@nih-nci-dceg-connect-prod-6d04.iam.gserviceaccount.com']
          
images:
 - 'gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-weekly-report-api:$COMMIT_SHA'